version: '2'

services:
    frontend:
        image: nginx:latest
        container_name: intertech_frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx/frontend.local.conf:/etc/nginx/conf.d/frontend.local.conf.template
            - ./conf/nginx/frontend.production.conf:/etc/nginx/conf.d/frontend.production.conf.template
            - ./frontend:/var/www
            - ./backend/storage/app:/home
            - ./logs/nginx/frontend:/var/log/nginx
            - ./certificates:/etc/letsencrypt
        env_file: .env
        command: /bin/bash -c "rm /etc/localtime && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && envsubst '$$APP_SERVER_NAME_FRONTEND' < /etc/nginx/conf.d/frontend.$APP_ENV.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        links:
            - frontend_php
        tty: true
        networks:
            - app-net

    frontend_php:
        build: ./php
        container_name: intertech_frontend_php
        volumes:
            - ./frontend:/var/www
            - ./logs/php/frontend:/var/log/php
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/custom_vars.ini
        links:
            - mysql
            - memcached
        env_file: .env
        networks:
            - app-net

    backend:
        image: nginx:latest
        container_name: intertech_backend
        ports:
            - "81:80"
        volumes:
            - ./conf/nginx/backend.local.conf:/etc/nginx/conf.d/backend.local.conf.template
            - ./conf/nginx/backend.production.conf:/etc/nginx/conf.d/backend.production.conf.template
            - ./backend:/var/www
            - ./logs/nginx/backend:/var/log/nginx
            - ./certificates:/etc/letsencrypt
        env_file: .env
        command: /bin/bash -c "rm /etc/localtime && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && envsubst '$$APP_SERVER_NAME_BACKEND' < /etc/nginx/conf.d/backend.$APP_ENV.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        links:  
            - backend_php
        tty: true
        networks:
            - app-net

    backend_php:
        build: ./php
        container_name: intertech_backend_php
        volumes:
            - ./backend:/var/www
            - ./logs/php/backend:/var/log/php
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/custom_vars.ini
        links:
            - mysql
            - memcached
        env_file: .env
        networks:
            - app-net

    mysql:
        hostname: mysql
        container_name: intertech_mysql
        build: ./mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
            - ./logs/mysql:/var/log/mysql
        env_file: .env
        networks:
            - app-net

    memcached:
        hostname: memcached
        image: memcached
        container_name: intertech_memcached
        networks:
            - app-net
        ports:
            - "11211:11211"

networks:
    app-net:
        driver: bridge